import smartTV as st

# my4KTv = st.Tv4k('65', 'silver', '4k')
# my4KTv.setSmartTv('on')
# my4KTv.turnOn()
# my4KTv.turnOff()
# my4KTv.printTvInfo()
# print('-' * 50)
# friend4KTv = st.Tv4k('55', 'white', '4k')
# friend4KTv.setSmartTv('off')
# friend4KTv.turnOn()
# friend4KTv.turnOff()
# friend4KTv.printTvInfo()
my84KTv = st.Tv8k('75', 'black', '8k')
my84KTv.setSmartTv('on')
my84KTv.setAiTv('on')
my84KTv.turnOn()
my84KTv.turnOff()
my84KTv.printTvInfo()